[package]
name = "xtask"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "3.0"
