[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"

[target.x86_64-pc-windows-gnu]
linker = "lld"

[target.aarch64-pc-windows-msvc]
linker = "lld-link"

[profile.dev.package."*"]
opt-level = 1

[profile.dev]
opt-level = 0
debug = true
codegen-units = 16
lto = "off"

[profile.release]
opt-level = 3
debug = false
strip = true
lto = "thin"
codegen-units = 1
panic = "abort"

[registries.crates-io]
protocol = "sparse"

[alias]
xtask = "run --package xtask -- "
