name: Code Quality Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install mold
        run: sudo apt-get update && sudo apt-get install -y mold

      - name: Build
        run: cargo build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install mold
        run: sudo apt-get update && sudo apt-get install -y mold

      - name: Run Tests
        run: cargo test --workspace

  format:
    name: Format
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          cache: true

      - name: Check formatting
        run: cargo fmt --all -- --check

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache: true

      - name: Install mold
        run: sudo apt-get update && sudo apt-get install -y mold

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  dependencies:
    name: Dependencies
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install cargo-deny
        run: cargo install --locked cargo-deny

      - name: Check Dependencies
        run: cargo deny check

  audit:
    name: Dependencies Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install cargo-audit
        run: cargo install --locked cargo-audit

      - name: Security Audit
        run: cargo audit
